Provide PHP 8.1 support
laminas/laminas-soap pull request #31
Opened 2021-10-12 22:42 UTC by weierophinney

This patch provides PHP 8.1 support for laminas-soap via the following changes:

- It adds `~8.1.0` to the list of supported PHP versions
- It **drops support for PHP 7.3**
- It changes how the package replaces zend-soap:
  - It renames the "replace" section to "conflict"
  - It changes the "zend-soap" entry in that section to have the constraint "*"
  - It removes the dependency on laminas-zendframework-bridge
- It adds `#[ReturnTypeWillChange]` attributes to the `Client` implementation where it overrides internal methods.
- It updates test assets to follow internal signatures.
- It adds Laminas CI configuration and pre-run scripts to allow testing against PHP 8.1.

2021-10-13 06:14 UTC, Ocramius requested changes

2021-10-13 06:14 UTC, Ocramius commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
Hmm, why is laminas-code needed?

2021-10-13 09:59 UTC, froschdesign commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
laminas-server uses laminas-code:

https://github.com/laminas/laminas-soap/blob/f4cff0772a8fc92ad1f841c0c8ab0b0f269c7dbc/composer.json#L21-L29

This pull request contains also an update for this:

```json
"laminas/laminas-server": "^2.11",
```

But I don't know why version 4.4 is explicitly installed in the pre-run script.

2021-10-13 10:13 UTC, Ocramius commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
But why is `laminas-code` not in `composer.json` then? :|

2021-10-13 10:20 UTC, froschdesign commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
Maybe wrong version, see in laminas-server: :confused:

```json
"require": {
    "php": "^7.3 || ~8.0.0 || ~8.1.0",
    "laminas/laminas-code": "^3.5.1 || ^4.0.0",
    "laminas/laminas-stdlib": "^3.3.1"
},
```

https://github.com/laminas/laminas-server/blob/3.0.x/composer.json#L21-L25

2021-10-13 11:34 UTC, Ocramius commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
We could declare a `"conflict": {"laminas/code": "<4.4"}` here instead, which is a bit healthier...

2021-10-13 13:18 UTC, weierophinney commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
Here's the situation:

laminas-server's latest release works against PHP 7.3 - 8.1. It depends on laminas-code 3.5 or 4.0. Since it's a _direct_ requirement, when Composer is resolving while running on PHP 8.1, it will pull a version that works with 8.1 even when the `--prefer-lowest` flag is used.

However, since laminas-code is a sub-dependency for laminas-soap (which depends on laminas-server), those same flags end up pulling the lowest supported version, in this case the 3.5.x releases. Those do NOT work with PHP 8.1, so I end up with deprecation notices.

If I were to do a "conflict" rule as you suggest, I'd also need to bump the minimum supported PHP version to 7.4 for this release, which feels off, as laminas-server doesn't have that same stipulation. So the pre-run hack was the workaround I used to ensure we get laminas-code >= 4.4.0 when running via lowest dependencies.

I can certainly bump the minimum supported PHP version here; I was mainly trying to keep parity with what laminas-serve supports.

2021-10-13 14:36 UTC, Ocramius commented on .laminas-ci/pre-run.sh
> +composer require "laminas/laminas-code:^4.4" --ignore-platform-req=php
> If I were to do a "conflict" rule as you suggest, I'd also need to bump the minimum supported PHP version to 7.4 for this release, which feels off, as laminas-server doesn't have that same stipulation.

It wouldn't be a suggestion: it would be a requirement.

Also: YOLO. Ain't nobody got time for PHP 7.3.

2021-10-13 20:32 UTC, weierophinney commented
@Ocramius Okay, finished it up. The bump to 7.4 meant I needed to bump the CS version from the v1 series to the v2 series, which meant a lot more changes overall; I tried to do granular commits, with one being just the dep bump, the next applying autofixes and correcting stuff phpcs couldn't autofix, the next taking care of the remaining file-level docblocks, and finally "fixing" the PHPUnit bootstrap.

2021-10-14 14:04 UTC, Ocramius approved these changes
Didn't find anything dangerous in the diff (mostly looking for `==` to `===` changes, which are always a bit risky).

:ship: 

Thanks @weierophinney!

2021-10-14 14:04 UTC, merged